version: "3"

volumes:
  node_modules:
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # - '80:80'
      - "$PORT:$PORT" # /80/81/5000/20385
    env_file:
      - .env
    command:
      - bash
      - -c
      - |
        npm run release
        cd buildpack-nginx/ && bin/compile /app && cd ..
        env
        bin/start-nginx node start.js
    # depends_on:
    #   - server
    volumes:
      - .:/app
      # - ./config/sockets:/tmp # Error: listen EIO: i/o error /tmp/nginx.socket
      - node_modules:/app/node_modules/
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   container_name: nginx-proxy
  #   hostname: nginx-proxy
  #   volumes:
  #     - ./public_html:/home/public_html:ro
  #     - ./run/main:/tmp:rw
  #     - ./nginx/conf.d:/etc/nginx/conf.d:rw
  #   ports:
  #     - 80:80
  #   restart: always # unless-stopped
  # public:
  #   build:
  #     context: ./packages/client/public
  #     dockerfile: Dockerfile
  #   # env_file:
  #   #   - packages/client/public/.env
  #   # command:
  #   #   - sh
  #   #   - -c
  #   #   - |
  #   #     env
  #   container_name: internal-${HOST_NAME_PUBLIC}
  #   hostname: internal-${HOST_NAME_PUBLIC}
  #   volumes:
  #     - ./public_html/${HOST_NAME_PUBLIC}:/home/public_html:rw
  #     - ./run/main/${HOST_NAME_PUBLIC}:/tmp:rw
  #   environment:
  #     - HOST_NAME_PUBLIC=${HOST_NAME_PUBLIC}
  #   restart: unless-stopped # always
