version: '3'

volumes:
  node_modules:
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # - '80:80'
      - '$PORT:$PORT' # /80/81/5000/20385
    env_file:
      - .env
    command:
      - bash
      - -c
      - |
        # npm run release
        cd buildpack-nginx/ && bin/compile /app && cd ..
        env
        bin/start-nginx node start.js
    # depends_on:
    #   - server
    volumes:
      - .:/app
      # - ./config/sockets:/tmp # Error: listen EIO: i/o error /tmp/nginx.socket
      - node_modules:/app/node_modules/
