name: Check Changelog

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug
        run: |
          echo "GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH=${GITHUB_EVENT_PATH}"
          cat "${GITHUB_EVENT_PATH}" | jq .
        # run: |
        #   cat $GITHUB_EVENT_PATH | jq .pull_request.title |  grep -i '\[\(\(changelog skip\)\|\(ci skip\)\)\]' ||  git diff remotes/origin/${{ github.base_ref }} --name-only | grep changelog.md
        # run: cat $GITHUB_EVENT_PATH | jq -c '.pull_request.url + "/files"' | xargs curl --silent |  jq -c 'map(.filename)' | grep -q 'CHANGELOG.md'
      # - name: Check that CHANGELOG is touched
