name: Check Changelog

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: debug
        run: |
          echo "GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH=${GITHUB_EVENT_PATH}"
          cat "${GITHUB_EVENT_PATH}" | jq .
      - name: Check that CHANGELOG is touched
        run: |
          cat $GITHUB_EVENT_PATH | jq .pull_request.title |  grep -i '\[\(\(changelog skip\)\|\(ci skip\)\)\]' ||  git diff remotes/origin/${{ github.base_ref }} --name-only | grep changelog.md
